question_data = [
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Books",
          "question": "Elementary, my dear Watson is a phrase that is never truly said within the Conan "
                      "Doyle books of Sherlock Holmes.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Sports",
          "question": "In Rugby League, performing 40-20; is punished by a free kick for the opposing team.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "History",
          "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
          "question": "The Sun rises from the North.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "History",
          "question": "Thomas Crapper was a plumber who invented the flushing toilet.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "In the Half-Life series; H.E.V; stands for; Hazardous Evasiveness Vest",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "In the game Subnautica;, a Spadefish will attack you.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
          "question": "Food fight! earned less than $80,000 at box office.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "In Need for Speed: Porsche Unleashed;, the player can only drive cars manufactured by Porsche.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Animals",
          "question": "The Killer Whale is considered a type of dolphin.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "History",
          "question": "The Spitfire originated from a racing plane.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
          "question": "The Windows ME operating system was released in the year 2000.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
          "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Geography",
          "question": "Nova Scotia is on the east coast of Canada.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "Niko Bellic is the protagonist of Grand Theft Auto IV.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
          "question": "Pluto is a planet.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Music",
          "question": "Korean girl group, TWICE, consists of 9 members",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "The ultimate phrase used by Pharah from Overwatch is: Justice rains from above!&quot;",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy",
          "category": "Entertainment: Japanese Anime &amp; Manga",
          "question": "Studio Ghibli is a Japanese animation studio responsible for the films Wolf Children and The Boy and the Beast.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy",
          "category": "Entertainment: Cartoon &amp; Animations",
          "question": "Bill Cipher in the show Gravity Falls is the good guy.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Politics",
          "question": "The S in Harry S. Truman stands for Samuel.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "In Super Mario Bros., the clouds and bushes have the same artwork and are just different colors.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
          "question": "Celiac Disease is a disease that effects the heart, causing those effected to be unable to eat "
                      "meat.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Politics",
          "question": "Russia passed a law in 2013 which outlaws telling children that homosexuals exist.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
          "question": "HTML stands for Hypertext Markup Language.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
          "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
          "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "easy",
                                           "category": "Entertainment: Japanese Anime &amp; Manga",
                                           "question": "Kiznaiver is an adaptation of a manga.",
                                           "correct_answer": "False",
                                           "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "In Pokemon Sun and Moon, a male Salandit can evolve to a Salazzle.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "The shotgun appears in every numbered Resident Evil game.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Geography",
          "question": "There are no deserts in Europe.", "correct_answer": "True",
          "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Geography",
          "question": "Greenland is almost as big as Africa.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "Half-Life 2 runs on the Source Engine.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Geography",
          "question": "San Marino is the only country completely surrounded by another country.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy",
          "category": "Entertainment: Japanese Anime &amp; Manga",
          "question": "In the Toaru Kagaku no Railgun anime,  espers can only reach a maximum of level 6 in their abilities.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
          "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
          "question": "Matt Damon played an astronaut stranded on an extraterrestrial planet in both of the movies Interstellar and The Martian.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
          "question": "Scotland voted to become an independent country during the referendum from September 2014.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Television",
          "question": "In Star Trek, Klingons are aliens.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
          "question": "Time on Computers is measured via the EPOX System.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "History",
          "question": "The United States of America was the first country to launch a man into space.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "Peter Molyneux was the founder of Bullfrog Productions.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy", "category": "Geography",
          "question": "Greenland is covered with grass and Iceland covered with ice.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "The name of the main character of the video game The Legend of Zelda, is Zelda.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
          "question": "The word Inception came from the 2010 blockbuster hit Inception.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
          "question": "The main character in the Half-Life franchise is named Morgan Freeman.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Sports",
          "question": "Roger Federer is a famous soccer player.", "correct_answer": "False",
          "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
          "question": "The film 2001: A Space Odyssey was released on December 31st, 2000.",
          "correct_answer": "False", "incorrect_answers": ["True"]},
         {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
          "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after "
                      "filming.",
          "correct_answer": "True", "incorrect_answers": ["False"]},
         {"type": "boolean", "difficulty": "easy",
          "category": "Entertainment: Japanese Anime &amp; Manga",
          "question": "The anime Lucky Star follows the story of one girl who is unaware she is God.",
          "correct_answer": "False", "incorrect_answers": ["True"]}
]
